name: Build
on:
  push:
    branches: 
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: tomcat
          tags: latest
          enableBuildKit: true
          buildArgs: GPG_KEY_URL="https://github.com/slurmorg/build-containers-trusted/raw/main/key.gpg" ,ROOTFS_URL="https://github.com/slurmorg/build-containers-trusted/raw/main/rootfs.tar.gz"
            MAVEN_URL="https://github.com/slurmorg/build-containers-trusted/raw/main/apache-maven-3.9.1-bin.tar.gz"
            TOMCAT_URL="https://github.com/slurmorg/build-containers-trusted/raw/main/apache-tomcat-10.1.7.tar.gz"
            FINGERPRINT="70092656FB28DBB76C3BB42E89619023B6601234"
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      
